### ISSUE TITLE
Make a generic link shortcode

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#410]
## User story

We could do with a way to make any generic link look like a CTA (and not link to kofi etc)

[Motivation](https://github.com/geeksforsocialchange/gfsc-v3/pull/409#issuecomment-2186288919)

## Acceptance criteria

- [ ] There is a generic cta shortcode
- [ ] CSS is consistent across all buttons (i.e. prob let's not call the class `.kofi`)
- [ ] Any existing manually created buttons are shifted to the shortcode

## Implementation plan
