### ISSUE TITLE
Fix image shortcodes

### ISSUE THREAD

**Issue by jazzchatfield** [geeksforsocialchange/gfsc-v3#42]
## User story

As a person updating the site I need to be able to add images in a way that makes sense so that I do not lose my mind.

## Acceptance criteria

- [ ] It is easy to tell which image shortcodes to use for different scenarios
- [ ] The image shortcodes work as they should

## Implementation notes & questions

```
the current image partial is a fucking tire fire and it prob needs a rethink rather than just porting across as is lol (this is entirely my fault) - kim
```

https://gohugo.io/templates/shortcode-templates/

## Implementation plan

- [ ] Seperate into 'image' and 'gallery' with either entirely named or combo of named/positional parameters ('flexible' as per Hugo docs
