### ISSUE TITLE
Epic: Comb through all layouts to finalise styling

### ISSUE THREAD

**Issue by jazzchatfield** [geeksforsocialchange/gfsc-v3#81]
## Description

The rough styling is in place, but some bits were left for later and need tweaking/perfecting.

## Plan

- Compare to XD file at all 4 screen sizes
- Check against responsive sizes
- Tweak styling/HTML as needed

## Sub tasks

- [ ] Header
- [ ] Footer
- [ ] Homepage
- [ ] Blog index
- [ ] Blog post
- [ ] Theme/category page
- [ ] Studio
- [ ] Collective
- [ ] Our work page
- [ ] Individual project page
- [ ] Team page
- [ ] Contact page
